# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/VisualizerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import visualizer


class Ui_VisualizerDialog(object):
    def setupUi(self, VisualizerDialog):
        VisualizerDialog.setObjectName("VisualizerDialog")
        VisualizerDialog.resize(350, 200)
        VisualizerDialog.setMinimumSize(QtCore.QSize(350, 200))
        VisualizerDialog.setMaximumSize(QtCore.QSize(350, 200))
        font = QtGui.QFont()
        font.setFamily("Fira Mono Medium")
        font.setPointSize(12)
        VisualizerDialog.setFont(font)
        VisualizerDialog.setWindowOpacity(1.0)
        self.randomMaze_Checkbox = QtWidgets.QCheckBox(VisualizerDialog)
        self.randomMaze_Checkbox.setGeometry(QtCore.QRect(20, 120, 130, 30))
        self.randomMaze_Checkbox.setMinimumSize(QtCore.QSize(130, 30))
        self.randomMaze_Checkbox.setMaximumSize(QtCore.QSize(130, 30))
        self.randomMaze_Checkbox.setObjectName("randomMaze_Checkbox")
        self.quickVisualize_Checkbox = QtWidgets.QCheckBox(VisualizerDialog)
        self.quickVisualize_Checkbox.setGeometry(QtCore.QRect(20, 150, 170, 30))
        self.quickVisualize_Checkbox.setMinimumSize(QtCore.QSize(170, 30))
        self.quickVisualize_Checkbox.setMaximumSize(QtCore.QSize(170, 30))
        self.quickVisualize_Checkbox.setObjectName("quickVisualize_Checkbox")
        self.showGeneration_Checkbox = QtWidgets.QCheckBox(VisualizerDialog)
        self.showGeneration_Checkbox.setEnabled(False)
        self.showGeneration_Checkbox.setGeometry(QtCore.QRect(160, 120, 170, 30))
        self.showGeneration_Checkbox.setMinimumSize(QtCore.QSize(170, 30))
        self.showGeneration_Checkbox.setMaximumSize(QtCore.QSize(170, 30))
        self.showGeneration_Checkbox.setObjectName("showGeneration_Checkbox")
        self.visualize_Button = QtWidgets.QPushButton(VisualizerDialog)
        self.visualize_Button.setGeometry(QtCore.QRect(169, 60, 170, 50))
        self.visualize_Button.setMinimumSize(QtCore.QSize(170, 50))
        self.visualize_Button.setMaximumSize(QtCore.QSize(170, 50))
        self.visualize_Button.setObjectName("visualize_Button")
        self.gridSize_Combobox = QtWidgets.QComboBox(VisualizerDialog)
        self.gridSize_Combobox.setGeometry(QtCore.QRect(270, 20, 70, 30))
        self.gridSize_Combobox.setMinimumSize(QtCore.QSize(70, 30))
        self.gridSize_Combobox.setMaximumSize(QtCore.QSize(70, 30))
        self.gridSize_Combobox.setObjectName("gridSize_Combobox")
        self.gridSize_Combobox.addItem("")
        self.gridSize_Combobox.addItem("")
        self.gridSize_Combobox.addItem("")
        self.gridSize_Combobox.addItem("")
        self.gridSize_Combobox.addItem("")
        self.gridSize_Combobox.addItem("")
        self.gridSize_Combobox.addItem("")
        self.gridSize_Label = QtWidgets.QLabel(VisualizerDialog)
        self.gridSize_Label.setGeometry(QtCore.QRect(170, 20, 90, 30))
        self.gridSize_Label.setMinimumSize(QtCore.QSize(90, 30))
        self.gridSize_Label.setMaximumSize(QtCore.QSize(90, 30))
        self.gridSize_Label.setObjectName("gridSize_Label")
        self.algorithm_Label = QtWidgets.QLabel(VisualizerDialog)
        self.algorithm_Label.setGeometry(QtCore.QRect(10, 20, 90, 30))
        self.algorithm_Label.setMinimumSize(QtCore.QSize(90, 30))
        self.algorithm_Label.setMaximumSize(QtCore.QSize(90, 30))
        self.algorithm_Label.setObjectName("algorithm_Label")
        self.algorithm_Combobox = QtWidgets.QComboBox(VisualizerDialog)
        self.algorithm_Combobox.setGeometry(QtCore.QRect(10, 60, 150, 50))
        self.algorithm_Combobox.setMinimumSize(QtCore.QSize(150, 50))
        self.algorithm_Combobox.setMaximumSize(QtCore.QSize(150, 50))
        self.algorithm_Combobox.setObjectName("algorithm_Combobox")
        self.algorithm_Combobox.addItem("")
        self.algorithm_Combobox.addItem("")
        self.algorithm_Combobox.addItem("")
        self.algorithm_Combobox.addItem("")

        self.retranslateUi(VisualizerDialog)
        QtCore.QMetaObject.connectSlotsByName(VisualizerDialog)

        ## Added functionality ##
        self.visualize_Button.clicked.connect(self.visualizeButtonPressed)
        self.randomMaze_Checkbox.stateChanged.connect(self.randomMazeStateChanged)

    def visualizeButtonPressed(self):
        flags = 0b000
        if self.quickVisualize_Checkbox.checkState() == 2:  # so if it is activated
            flags += visualizer.QUICK_SOLVE
        if self.randomMaze_Checkbox.checkState() == 2:
            flags += visualizer.RANDOM_MAZE
        if self.showGeneration_Checkbox.checkState() == 2:
            flags += visualizer.SHOW_GENERATION
        visualizer.run(int(self.gridSize_Combobox.currentText()), self.algorithm_Combobox.currentText(), flags)

    def randomMazeStateChanged(self):
        if self.randomMaze_Checkbox.isChecked():
            self.showGeneration_Checkbox.setEnabled(True)
        else:
            self.showGeneration_Checkbox.setChecked(False)
            self.showGeneration_Checkbox.setEnabled(False)

    def retranslateUi(self, VisualizerDialog):
        _translate = QtCore.QCoreApplication.translate
        VisualizerDialog.setWindowTitle(_translate("VisualizerDialog", "Pathfinding Visualizer"))
        self.randomMaze_Checkbox.setText(_translate("VisualizerDialog", "Random Maze"))
        self.quickVisualize_Checkbox.setText(_translate("VisualizerDialog", "Quick Visualize"))
        self.showGeneration_Checkbox.setText(_translate("VisualizerDialog", "Show Generation"))
        self.visualize_Button.setText(_translate("VisualizerDialog", "Visualize"))
        self.gridSize_Combobox.setItemText(0, _translate("VisualizerDialog", "21"))
        self.gridSize_Combobox.setItemText(1, _translate("VisualizerDialog", "27"))
        self.gridSize_Combobox.setItemText(2, _translate("VisualizerDialog", "35"))
        self.gridSize_Combobox.setItemText(3, _translate("VisualizerDialog", "45"))
        self.gridSize_Combobox.setItemText(4, _translate("VisualizerDialog", "63"))
        self.gridSize_Combobox.setItemText(5, _translate("VisualizerDialog", "105"))
        self.gridSize_Combobox.setItemText(6, _translate("VisualizerDialog", "135"))
        self.gridSize_Label.setText(_translate("VisualizerDialog", "Grid Size"))
        self.algorithm_Label.setText(_translate("VisualizerDialog", "Algorithm"))
        self.algorithm_Combobox.setItemText(0, _translate("VisualizerDialog", "BFS"))
        self.algorithm_Combobox.setItemText(1, _translate("VisualizerDialog", "DFS"))
        self.algorithm_Combobox.setItemText(2, _translate("VisualizerDialog", "A*"))
        self.algorithm_Combobox.setItemText(3, _translate("VisualizerDialog", "Dijkstra"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VisualizerDialog = QtWidgets.QDialog()
    ui = Ui_VisualizerDialog()
    ui.setupUi(VisualizerDialog)
    VisualizerDialog.show()
    sys.exit(app.exec_())
